springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

service-bus:
  connection-string: ${SERVICEBUS_CONNECTIONSTRING}
  order-placed-queue-name: ${ORDER_PLACED_QUEUE_NAME:order-placed-sbq}

cosmos-db:
  uri: ${COSMOSDB_URI}
  key: ${COSMOSDB_KEY}
  database: ${COSMOSDB_DATABASE}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
